name: Release RedSky

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: wangyoucao577/go-release-action@481a2c1a0f1be199722e3e9b74d7199acafc30a8 # v1.53
        with:
          ldflags: -X github.com/prdngr/red-sky/internal.buildCommit=${{ github.sha }} -X github.com/prdngr/red-sky/internal.buildVersion=${{ github.event.release.tag_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
